# version: "2.4"
services:
  hma_wrs_sim_ws:
    build: .
    image: hma_wrs_sim_ws:latest
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    environment:
      ROS_MASTER_URI:
      ROS_IP:
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: all
      DISPLAY: 
      QT_X11_NO_MITSHM: 1
      NVIDIA_VISIBLE_DEVICES: 0
    network_mode: "host"
    volumes:
      - ./src:/home/ros_ws/hma/hma_wrs_sim_ws/src
      - ./entrypoints:/entrypoints
      - ./.bashrc_hma:/root/.bashrc_hma
      - /tmp/.X11-unix:/tmp/.X11-unix
    runtime: nvidia
    privileged: true
    stdin_open: true
    tty: true
    entrypoint: ["bash"]